### ISSUE TITLE
Unable to install `fbow-stella` from source

### ISSUE THREAD

**Issue by erwin-wu-x** [zicklag/zicklag-forge#1]
Hi @zicklag,

Great work, and thank you for your efforts in improving the community!

I'm currently attempting to install `fbow-stella` and `stella_slam` from your source package. I've tried two different configurations in my `pixi.toml`, but both resulted in the same error.

### First `pixi.toml` attempt:

```toml
[project]
channels = ["conda-forge", "https://prefix.dev/channels/zicklag-forge"]
name = "stella_vslam"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
fbow-stella = { version="0.0.1", build = "hb0f4dca_1", channel="https://prefix.dev/channels/zicklag-forge" }
```

After running `pixi install`, I encountered the following error:

```
Error:
  × could not find subdir 'noarch' in channel 'https://prefix.dev/channels/zicklag-forge/'
  ╰─▶ HTTP status client error (404 Not Found) for url (https://prefix.dev/channels/zicklag-forge/noarch/repodata.json)
```

### Second `pixi.toml` attempt:

I then modified the channel to `zicklag-forge` directly:

```toml
[project]
channels = ["conda-forge", "zicklag-forge"]
name = "stella_vslam"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
fbow-stella = { version="0.0.1", build = "hb0f4dca_1", channel="zicklag-forge" }
```

However, this resulted in a similar error:

```
Error:
  × could not find subdir 'noarch' in channel 'https://conda.anaconda.org/zicklag-forge/'
  ╰─▶ HTTP status client error (404 Not Found) for url (https://conda.anaconda.org/zicklag-forge/noarch/repodata.json)
```

It seems these issues might be due to the package configuration or availability on `prefix.dev`. Could you please take a look and help resolve this? Your assistance would be greatly appreciated.

Thanks again for your time and support!
